"""
Django settings for Coral project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hemj$98w_-e3ba1dsqww#cyi%u5sx&hqonqs5kpp8+i7k_e-kj"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "App",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Coral.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Add your custom context processors here
                "App.context_processors.global_services",
                "App.context_processors.global_counters",
                "App.context_processors.global_projects",
                "App.context_processors.global_minds",
                "App.context_processors.global_review",
                "App.context_processors.global_blogs",
                "App.context_processors.global_sliders",
                "App.context_processors.global_tables",
                "App.context_processors.global_traders",
                "App.context_processors.global_partners",
                "App.context_processors.global_counters2",
                "App.context_processors.global_portfolios",
                "App.context_processors.global_features",
                "App.context_processors.global_teams",
                "App.context_processors.global_sliders2",
                "App.context_processors.global_collections",
                "App.context_processors.global_portfolios2",
                "App.context_processors.global_hostings",
                "App.context_processors.global_counters3",
                "App.context_processors.global_counters4",
                "App.context_processors.global_navs",
                "App.context_processors.global_mondays",
                "App.context_processors.global_coaches",
                "App.context_processors.global_causes",
                "App.context_processors.global_volunteers",
                "App.context_processors.global_services2",
                "App.context_processors.global_teams2",
                "App.context_processors.global_reviews",
                "App.context_processors.global_reviews1",
                "App.context_processors.global_reviews2",
                "App.context_processors.global_wallets",
                "App.context_processors.global_creators",
                "App.context_processors.global_portfolios3",
                "App.context_processors.global_portfolios4",
                "App.context_processors.global_portfolios5",
                "App.context_processors.global_portfolios6",
                "App.context_processors.global_portfolios7",
                "App.context_processors.global_portfolios8",
                "App.context_processors.global_images",
                "App.context_processors.global_posts",
                "App.context_processors.global_tags",
                "App.context_processors.global_images2",
                "App.context_processors.global_contacts",
            ],
        },
    },
]

WSGI_APPLICATION = "Coral.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Added Manualy
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
